version: '3.8'

services:
  # Backend Service (Development)
  backend:
    build: .
    container_name: psa-backend-dev
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=True
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - SENDER_EMAIL=${SENDER_EMAIL}
      - EMAIL_APP_PASSWORD=${EMAIL_APP_PASSWORD}
      - DATABASE_URL=sqlite:///psa_incidents.db
      - LOG_LEVEL=DEBUG
    volumes:
      - .:/app
      - /app/__pycache__
    networks:
      - psa-network
    restart: unless-stopped
    command: python app_langgraph.py

  # Frontend Service (Development)
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: psa-frontend-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:5000
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - psa-network
    restart: unless-stopped
    command: npm run dev

  # Redis for development
  redis:
    image: redis:7-alpine
    container_name: psa-redis-dev
    ports:
      - "6379:6379"
    networks:
      - psa-network
    restart: unless-stopped

networks:
  psa-network:
    driver: bridge
